# Generated by Django 4.2.20 on 2025-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_purchaseorderitem_received_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['supply_name']},
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supply_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity to order'),
        ),
    ]
